# This should summon 6400 items (as 100 entities) at 0, 100, 0, letting
# them fall, and dropping TPS.

summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
summon minecraft:item 0 100 0 { Item: { id: "minecraft:stick", Count: 64b } }
