modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/RedstoneWizard08/Equivalence-Reborn/issues"

[[mods]]
modId="singularity"
version="${version}"
displayName="Singularity"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="icon.png"
#credits="Thanks for this example mod goes to Java"
authors="RedstoneWizard08, Bogdanasaurus"
#displayTest="MATCH_VERSION"

description='''

'''

[[dependencies.singularity]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.singularity]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.singularity]]
modId="cloth_config"
type="required"
versionRange="[8.2,)"
ordering="NONE"
side="BOTH"
