name: Publish on GitHub, CurseForge & Modrinth

on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.21.1
  JAVA_VERSION: 21
  VERSION: 0.6.0
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth/GitHub) (FORGE)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 968634
          curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"

          modrinth-id: S5dPX47J
          modrinth-token: "${{ env.MODRINTH_TOKEN }}"

          github-tag: "v${{ env.VERSION }}"
          github-token: "${{ env.GITHUB_TOKEN }}"

          name: "${{ env.VERSION }}+forge-${{ env.MINECRAFT_VERSION }}"
          version: "${{ env.VERSION }}"
          version-type: beta

          loaders: forge
          game-versions: "${{ env.MINECRAFT_VERSION }}"
          java: "${{ env.JAVA_VERSION }}"

          files: |
            forge/build/libs/Singularity-${{ env.VERSION }}+forge-${{ env.MINECRAFT_VERSION }}-all.jar

      - name: Publish (CurseForge/Modrinth/GitHub) (NEOFORGE)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 968634
          curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"

          modrinth-id: S5dPX47J
          modrinth-token: "${{ env.MODRINTH_TOKEN }}"

          github-tag: "v${{ env.VERSION }}"
          github-token: "${{ env.GITHUB_TOKEN }}"

          name: "${{ env.VERSION }}+neoforge-${{ env.MINECRAFT_VERSION }}"
          version: "${{ env.VERSION }}"
          version-type: beta

          loaders: neoforge
          game-versions: "${{ env.MINECRAFT_VERSION }}"
          java: "${{ env.JAVA_VERSION }}"

          files: |
            neoforge/build/libs/Singularity-${{ env.VERSION }}+neoforge-${{ env.MINECRAFT_VERSION }}-all.jar

      - name: Publish (CurseForge/Modrinth/GitHub) (FABRIC)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 968634
          curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"

          modrinth-id: S5dPX47J
          modrinth-token: "${{ env.MODRINTH_TOKEN }}"

          github-tag: "v${{ env.VERSION }}"
          github-token: "${{ env.GITHUB_TOKEN }}"

          name: "${{ env.VERSION }}+fabric-${{ env.MINECRAFT_VERSION }}"
          version: "${{ env.VERSION }}"
          version-type: beta

          loaders: fabric
          game-versions: "${{ env.MINECRAFT_VERSION }}"
          java: "${{ env.JAVA_VERSION }}"

          files: |
            fabric/build/libs/Singularity-${{ env.VERSION }}+fabric-${{ env.MINECRAFT_VERSION }}-all.jar